version: "3.9"

services:
  my_server:
    build:
      context: .
      dockerfile: ./docker/my_server_dockerfile
    image: myserver-web:latest
    ports:
      - 8000:8000
    healthcheck:
        test: ["CMD", "curl", "-f", "${SERVER_URL}"]
        interval: 10s
        timeout: 2s
        retries: 5
  
  robot:
    build:
      context: .
      dockerfile: ./docker/robot_dockerfile
    image: myserver-tests:latest
    volumes:
      - ./output/:/robot_tests/output/*
    depends_on:
      - my_server
    environment:
      - SERVER_URL

  
    